/**
* The sequence of triangle numbers is generated by adding the natural numbers.
* So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
*
* The first ten terms would be:
*                               1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
*
* Let us list the factors of the first seven triangle numbers:
*  1: 1
*  3: 1,3
*  6: 1,2,3,6
* 10: 1,2,5,10
* 15: 1,3,5,15
* 21: 1,3,7,21
* 28: 1,2,4,7,14,28
*
* We can see that 28 is the first triangle number to have over five divisors.
*
* What is the value of the first triangle number to have over five hundred divisors?
* 
* Answer: "76576500"
* Took around 15 minutes with this crude method.
*/

#include <stdio.h>

int get_factors(int number);

int main(int argc, char* argv[])
{
	printf("Solving problem 12!\n");
    
    int index = 1;
    int cur_num = 0;
    int done = 0;
    int num_factors = 0;

    while(!done)
    {
        cur_num = cur_num + index;  //add the next integer to the current triangle number
        index++;
        num_factors = get_factors(cur_num);
        if(num_factors > 200)
        {
            printf("%d: %d factors.\n", cur_num, num_factors);
        }
        if(num_factors > 500)
        {
            done = 1;
        }
    }

	return 0;
}


int get_factors(int number)
{
    int index = 1;
    int num_factors = 0;
    while(index <= number)  //todo: probably can optimize this
    {
        if(number%index == 0)
        {
            num_factors++;
        }
        index++;
    }
    return num_factors;
}

