/**
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not 
 * exceed four million.
 * 
 * Answer: "4613732"
 */

package problem_002;


/**
 * TODO Comment this class
 * @author Michael Patterson
 *
 */
public class Problem_002_Solver 
{
	
	public static void main(String[] args)
	{
		
		int sum = 0;
		int first = 0;
		int second = 1;
		int nextFibNum = 0;
		
		while(true)
		{//run until break statement
			nextFibNum = first + second;
			first = second;
			second = nextFibNum;
			
			if(nextFibNum > 4000000)
				break;
			
			if(nextFibNum % 2 == 0)
			{
				sum += nextFibNum;
			}
		}
		System.out.println(sum);
	}
}
