# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# 
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

def tri(n):
    num =  n * (n + 1) / 2
    return int(num)

def pen(n):
    num =  n * ((3 * n) - 1) / 2
    return int(num)

def hexa(n):
    num =  n * ((2 * n) - 1)
    return int(num)

def solve(starting_triangle_index):
    tri_i = starting_triangle_index
    pen_i = 2
    hexa_i = 2
    while True:
        cur_tri = tri(tri_i)
        cur_pen = pen(pen_i)
        cur_hexa = hexa(hexa_i)
        if cur_tri < cur_pen:
            tri_i += 1
        elif cur_pen < cur_tri:
            pen_i += 1
        else:
            if cur_hexa > cur_tri:
                tri_i +=1
            elif cur_hexa < cur_tri:
                hexa_i +=1
            else:
                break
    return cur_tri


if __name__ == '__main__':
    print(solve(286))
