# 
# 
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
# 
from itertools import combinations

def pent(n):
    return int(n * (3 * n - 1) / 2)

def solve():
    ps = set(pent(n) for n in range(1, 10001))
    for j, k in combinations(ps, 2):
        if (j + k) in ps and abs(k - j) in ps:
            return(abs(j - k))


if __name__ == '__main__':
    print(solve())
